-- Add explanation column to flashcards table
ALTER TABLE flashcards
ADD COLUMN explanation TEXT;

COMMENT ON COLUMN flashcards.explanation IS 'Pedagogical explanation, tip, or cultural note generated by AI';
