-- Migration: Initial Weekly Plan Trigger
-- Created: 2026-02-24
-- Description: Automatically generates first weekly plan when user profile is created

-- ============================================================================
-- FUNCTION: Check and Generate Initial Plan (Simpler Approach)
-- ============================================================================
-- This function will be called by the app when user first accesses the plan screen

DROP FUNCTION IF EXISTS public.ensure_weekly_plan_exists(uuid);

CREATE OR REPLACE FUNCTION public.ensure_weekly_plan_exists(p_user_id UUID)
RETURNS TABLE (
  out_plan_id UUID,
  out_week_start DATE,
  out_status TEXT,
  out_message TEXT
) AS $$
DECLARE
  v_selected_week DATE;
  v_existing_plan UUID;
  v_profile RECORD;
  v_snapshot_id UUID;
BEGIN
  -- Calculate current week start (Monday)
  v_selected_week := date_trunc('week', CURRENT_DATE)::DATE;
  
  -- Check if active plan exists
  SELECT id INTO v_existing_plan
  FROM public.weekly_plans wp
  WHERE wp.user_id = p_user_id
    AND wp.status = 'active'
    AND wp.week_start = v_selected_week
  LIMIT 1;
  
  IF v_existing_plan IS NOT NULL THEN
    -- Plan already exists
    RETURN QUERY
    SELECT 
      v_existing_plan as out_plan_id,
      v_selected_week as out_week_start,
      'active'::TEXT as out_status,
      'Plan already exists'::TEXT as out_message;
    RETURN;
  END IF;
  
  -- Fetch user skill profile
  SELECT
      usp.user_id,
      usp.fluency_index,
      usp.primary_skill,
      usp.secondary_skill,
      usp.speaking_score,
      usp.grammar_score,
      usp.vocabulary_score,
      usp.listening_score,
      usp.fluency_score
  INTO v_profile
  FROM public.user_skill_profile usp
  WHERE usp.user_id = p_user_id;
  
  IF v_profile IS NULL THEN
    -- No profile yet, return null
    RETURN QUERY
    SELECT 
      NULL::UUID as out_plan_id,
      v_selected_week as out_week_start,
      'no_profile'::TEXT as out_status,
      'User skill profile not found'::TEXT as out_message;
    RETURN;
  END IF;
  
  -- Create snapshot if doesn't exist
  INSERT INTO public.weekly_skill_snapshot (
    user_id,
    week_start,
    fluency_index,
    primary_skill,
    secondary_skill,
    speaking_score,
    grammar_score,
    vocabulary_score,
    fluency_score,
    listening_score
  ) VALUES (
    p_user_id,
    v_selected_week,
    v_profile.fluency_index,
    v_profile.primary_skill,
    v_profile.secondary_skill,
    v_profile.speaking_score,
    v_profile.grammar_score,
    v_profile.vocabulary_score,
    v_profile.fluency_score,
    v_profile.listening_score
  )
  ON CONFLICT (user_id, week_start) DO UPDATE
  SET fluency_index = EXCLUDED.fluency_index
  RETURNING id INTO v_snapshot_id;
  
  -- Return indication that plan needs to be generated
  RETURN QUERY
  SELECT 
    NULL::UUID as out_plan_id,
    v_selected_week as out_week_start,
    'needs_generation'::TEXT as out_status,
    'Plan needs to be generated by AI'::TEXT as out_message;
  
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- GRANT PERMISSIONS
-- ============================================================================

GRANT EXECUTE ON FUNCTION public.ensure_weekly_plan_exists(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ensure_weekly_plan_exists(UUID) TO service_role;

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON FUNCTION public.ensure_weekly_plan_exists(UUID) IS 
'Checks if a weekly plan exists for the current week. If not, creates a snapshot and returns status indicating plan generation is needed.
This function is called by the app when user first accesses the plan screen to ensure they have a plan even if they signed up mid-week.';



