-- Migration: Initial Weekly Plan Trigger
-- Created: 2026-02-24
-- Description: Automatically generates first weekly plan when user profile is created

-- ============================================================================
-- FUNCTION: Check and Generate Initial Plan (Simpler Approach)
-- ============================================================================
-- This function will be called by the app when user first accesses the plan screen

CREATE OR REPLACE FUNCTION public.ensure_weekly_plan_exists(p_user_id UUID)
RETURNS TABLE (
  plan_id UUID,
  week_start DATE,
  status TEXT,
  message TEXT
) AS $$
DECLARE
  v_week_start DATE;
  v_existing_plan UUID;
  v_profile RECORD;
  v_snapshot_id UUID;
BEGIN
  -- Calculate current week start (Monday)
  v_week_start := date_trunc('week', CURRENT_DATE)::DATE;
  
  -- Check if active plan exists
  SELECT id INTO v_existing_plan
  FROM public.weekly_plans
  WHERE user_id = p_user_id
    AND status = 'active'
    AND week_start = v_week_start
  LIMIT 1;
  
  IF v_existing_plan IS NOT NULL THEN
    -- Plan already exists
    RETURN QUERY
    SELECT 
      v_existing_plan,
      v_week_start,
      'active'::TEXT,
      'Plan already exists'::TEXT;
    RETURN;
  END IF;
  
  -- Fetch user skill profile
  SELECT * INTO v_profile
  FROM public.user_skill_profile
  WHERE user_id = p_user_id;
  
  IF v_profile IS NULL THEN
    -- No profile yet, return null
    RETURN QUERY
    SELECT 
      NULL::UUID,
      v_week_start,
      'no_profile'::TEXT,
      'User skill profile not found'::TEXT;
    RETURN;
  END IF;
  
  -- Create snapshot if doesn't exist
  INSERT INTO public.weekly_skill_snapshot (
    user_id,
    week_start,
    fluency_index,
    primary_skill,
    secondary_skill,
    speaking_score,
    grammar_score,
    vocabulary_score,
    fluency_score,
    listening_score
  ) VALUES (
    p_user_id,
    v_week_start,
    v_profile.fluency_index,
    v_profile.primary_skill,
    v_profile.secondary_skill,
    v_profile.speaking_score,
    v_profile.grammar_score,
    v_profile.vocabulary_score,
    v_profile.fluency_score,
    v_profile.listening_score
  )
  ON CONFLICT (user_id, week_start) DO UPDATE
  SET fluency_index = EXCLUDED.fluency_index
  RETURNING id INTO v_snapshot_id;
  
  -- Return indication that plan needs to be generated
  RETURN QUERY
  SELECT 
    NULL::UUID,
    v_week_start,
    'needs_generation'::TEXT,
    'Plan needs to be generated by AI'::TEXT;
  
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- GRANT PERMISSIONS
-- ============================================================================

GRANT EXECUTE ON FUNCTION public.ensure_weekly_plan_exists(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ensure_weekly_plan_exists(UUID) TO service_role;

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON FUNCTION public.ensure_weekly_plan_exists(UUID) IS 
'Checks if a weekly plan exists for the current week. If not, creates a snapshot and returns status indicating plan generation is needed.
This function is called by the app when user first accesses the plan screen to ensure they have a plan even if they signed up mid-week.';



